pipeline {
    agent { label 'redhat-openshift' }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
                echo "Checked out code"
            }
        }
        stage('Build') {
            steps {
                echo "Building on node ${env.NODE_NAME}"
            }
        }
    }
}

