apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hulk-app
  name: bruce-banner
  namespace: the-incredible-hulk
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hulk-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hulk-app
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/shared-images/buggy-nginx:latest
        imagePullPolicy: Always
        name: nginx-container
        ports:
          - containerPort: 8000
        resources:
          requests:
            memory: "20Gi"
          limits:
            memory: "20Gi"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
