kind: Service
apiVersion: v1
metadata:
  name: hulk-svc
  namespace: the-incredible-hulk
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: hulk-app

